import type { Metadata } from "next";
import { Stack_Sans_Headline } from "next/font/google";
import "./globals.css";

const stackSans = Stack_Sans_Headline({
  subsets: ["latin"],
  variable: "--font-stack-sans",
  display: "swap",
});


export const metadata: Metadata = {
  title: "Mawida",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon-v2.ico",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" sizes="any" />
        <link rel="apple-touch-icon" href="/apple-touch-icon.png" />
        <link rel="manifest" href="/site.webmanifest" />
      </head>
      <body
        className={`${stackSans.variable} font-stack-sans antialiased`}
        suppressHydrationWarning
      >

        {children}
      </body>
    </html>
  );
}
